### PR TITLE
Fixed VS2022 Support

### LINKED ISSUE #40: Git Tools for Visual Studio 2022
Please let me know when you will have this code migrated for Visual Studio 2022 so that it can be installed.

### PR DESCRIPTION
**Pull request by NightOwl888**
Fixes #40.

This is built off of the https://github.com/yysun/git-tools/tree/VS2022 branch and also targets that branch.

I ended up rebuilding the whole project piece by piece from a working menu command demo, so I don't know all of the contributing factors that were causing it not to appear. But this PR:

1. Removes an unnecessary dependency on `WindowsBase.dll` from GitApi
2. Changed `UseCodeBase` to `true` - the menu disappeared when it was `false`
3. Changed `System.ComponentModel.Composition` to the NuGet package instead of GAC
4. Adds missing dependency on `Microsoft.VisualStudio.MefComponent` (which only seems to have fixed the colorization of the Git Diff window)

Performance is still an issue, but I tested a release build and it doesn't seem to be any worse than the VS2019 version. I suspect there are many performance issues that could be resolved by changing it to use [LibGit2Sharp](https://www.nuget.org/packages/LibGit2Sharp/) instead of `System.Diagnostics.Process` to run the git commands, using `await`, and not performing scans so frequently (or at least an option to disable it and use the refresh button manually).

On a large project, the scans interfere with the `Commit` button and it sometimes takes 10-15 clicks on it before it will take. The scans also interfere with trying to rewrite commit history.

At least this gets us off of VS2019, which has been out of support since April, 2022. Please roll a release ASAP.

### CODE REVIEW

**Comment by NightOwl888** [comment]
FYI - There is a [helpful VS2022 extension upgrade guide here](https://learn.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022).

**Comment by yysun** [comment]
Thank you very much.

**Comment by NightOwl888** [comment]
You're welcome.

I just realized I forgot to add the metadata to target other editions of Visual Studio 2022. It only included support for Visual Studio 2022 Community Edition.

**Comment by yysun** [comment]
I have added other editions in the published version.

**Pull request merged**
